# Generated by Django 3.0.5 on 2020-04-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='sections',
            field=models.ManyToManyField(blank=True, to='learning.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='resources',
            field=models.ManyToManyField(blank=True, to='learning.Resource'),
        ),
    ]
