# Generated by Django 3.0.5 on 2020-04-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
