# Generated by Django 3.0.5 on 2020-04-11 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='learning_unit',
        ),
        migrations.AddField(
            model_name='section',
            name='learning_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learning.LearningUnit'),
            preserve_default=False,
        ),
    ]
