# Generated by Django 3.0.5 on 2020-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20200411_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learning_units',
            field=models.ManyToManyField(blank=True, to='learning.LearningUnit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_sections',
            field=models.ManyToManyField(blank=True, to='learning.Section'),
        ),
    ]
