# Generated by Django 3.0.5 on 2020-04-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20200411_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
