name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Publish to Registry Nginx
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ secrets.DOCKER_REPOSITORY }}-nginx
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: nginx
        
    - name: Publish to Registry API
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ secrets.DOCKER_REPOSITORY }}-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: app
